### ISSUE TITLE
Run on Dedicated server

### ISSUE THREAD

**Issue by NoMerCyNL** [cloudmaker97/ls25-discord-bot#4]
Hello,

I've tried to install this on my dedicated server by Gportal.
Could add it to my discord, but there the bot was offline.

Maybe i miss something, but don't know how to install it by filezilla.

**Comment by cloudmaker97** [comment]
You need to run this on a server with Node or Docker running. Unless you start the bot via one of these both options the bot will not connect to discord and ain't running. The installation via FileZilla sounds not very common to my instructions in the README. If you need further support please consider contacting me via Discord: `cloudmaker97`

**Comment by NoMerCyNL** [comment]
Maybe i was thinking that it was needed to be installed on the game server. But what i understand now is that it can be installed on sperate nas with docker installed then?

**Comment by cloudmaker97** [comment]
You can install it on a dedicated game server as well, but you need root / supervisor access on the machine. Otherwise you could install it on a NAS with docker or rent a server with ssh/root.
